### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sverhagen/mp3-browser#38]
```
What steps will reproduce the problem?
1. Open page with mp3 Browser in Chrome
2. Click download icon

What is the expected output?
- Download

What do you see instead?
- Playback in new tab

Joomla 3.3.1, mp3 Browser 0.3.1

See #36

Happening in Chrome and Firefox. Not sure if this is a regression on the end of 
the plugin or a progression of these browsers.
```

Original issue reported on code.google.com by `sanderverh` on 17 Jun 2014 at 3:54

**Comment by sverhagen** [comment]
Solved in 0.4.0 ([released here](https://www.totaalsoftware.com/downloads/mp3-browser), [documented here](https://www.totaalsoftware.com/products/mp3-browser/documentation/195-download-files)).

But the absolute best solution is still to use content disposition (see [this comment](https://github.com/sverhagen/mp3-browser/issues/38#issuecomment-100602540)).
