### ISSUE TITLE
Cyrillic symbols become unreadable

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sverhagen/mp3-browser#39]
```
http://meditation.in.ua/mantry

Name of tracks become unreadable. Names are written in russian (cyrillic 
symbols), so we see "Òðåê 2" instead of "Трек 2"

Current version. Joomla 3.

```

Original issue reported on code.google.com by `inf...@iconsforvista.com` on 6 Jul 2014 at 9:47

Attachments:
- [Chaitanya_Nityananda.mp3](https://storage.googleapis.com/google-code-attachments/mp3-browser/issue-39/comment-0/Chaitanya_Nityananda.mp3)

**Comment by bizmarks** [comment]
I tried changing that setting but didn't do anything for me. Try changing the encoding in /etc/httpd/httpd.conf  by commenting utf8 encoding, then restart your server. You may also change .htaccess instead. A quick Google search will tell you the exact procedure.
