### ISSUE TITLE
my mp3 can't display chinese name

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sverhagen/mp3-browser#42]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?


Please provide any additional information below.


```

Original issue reported on code.google.com by `harrylin...@gmail.com` on 12 Aug 2014 at 3:33

**Comment by bizmarks** [comment]
See issue #61. My comment there may point you to the right direction. This has to do with Unicode. If you are on a Linux hosting server, you need to edit /etc/httpd/httpd.conf and uncomment the line that refers to utf8 encoding, then restart your server. If you are on a shared server and your host doesn't want to do this for you, you will have to edit .htaccess. A quick Google search will tell you where in .htaccess you will add Unicode support.
Hope this helps.
