### ISSUE TITLE
Blank page when show the "Extended Info" 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sverhagen/mp3-browser#46]
```
What steps will reproduce the problem?
1. Tick "Show" next to "Extended Info"
2. Save -> View Site
3. Go to article that should have table of MP3s

What is the expected output? 
A Table of MP3s

What do you see instead?
A Blank Page

What version of the product are you using? On what operating system?
Joomla - 3.3.3
mp3 Browser - 0.3.1
Tepmplate - Protostar

Please provide any additional information below.
My workaround was to change the MusicItem.php and HtmlNameColumn.php per my 
comment on Issue 33

sanderverh: Where do I find the logs you asked for in comment 17 of Issue 33?

```

Original issue reported on code.google.com by `jmckean...@gmail.com` on 20 Sep 2014 at 3:20

**Comment by bizmarks** [comment]
Go to your joomla configuration and set display errors to maximum or development mode. This will give you an error about a function that is not referenced or something to that effect. I can't remember but it is the code on one of the php files that is referencing to jbrowser. A quick Google search of the error will tell you what line to edit and what to replace it with. I'll get back to you on that to tell you exactly the procedure but this should point you to the right direction. Once corrections are made, blank page should go away. Afterwards, go back to global configuration and change display errors to none. As a rule of thumb, always display errors when you get a blank page, Google the error, apply fix and set display errors back to none, in joomla global configuration. Hope this helps...

**Comment by sverhagen** [comment]
Thank you, @bizmarks.
