### ISSUE TITLE
How to set the width of a column

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sverhagen/mp3-browser#52]
```
How can I set the width of column? Specifically, the Name column. I appears all 
the others are absolute, however the Name column adjusts automatically based on 
the text in the name.

http://2gncinfo.com/responsive/affiliate-resources.html

user: 2gnc
pw: 8463

Thanks!

Jason

```

Original issue reported on code.google.com by `elementa...@gmail.com` on 20 Nov 2014 at 12:23

**Comment by sverhagen** [comment]
Something like this might work, CSS:

    th:nth-child(2),
    tr td:nth-child(2) {
        max-width: ...
        width: ...
    }

It becomes probably more tricky when you enable extended info. The notion of columns and width evaporates a bit then, since it's not a straight column, but cells composed of two out three columns, blah-blah. I lost you.
