### ISSUE TITLE
Hide "Name" and "Play" header

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sverhagen/mp3-browser#59]
```
Hello, how can I hide the header with "Name" and "Play"? Thanks!

```

Original issue reported on code.google.com by `berom...@gmail.com` on 23 Apr 2015 at 9:44

**Comment by sverhagen** [comment]
A cheap solution may be with CSS:

    .mp3browser th:nth-child(2),
    .mp3browser th:nth-child(3) {
        color: #d0d0d0;
    }

Another solution may be changing PHP: find `HtmlNameColumn` and `HtmlPlayerColumn` respectively, and change the method `getHeaderText` to return an empty string or `"&nbsp;"`.
