### ISSUE TITLE
MPbrowser does not play unicode names

### ISSUE THREAD

**Issue by bizmarks** [sverhagen/mp3-browser#61]
Hi,
Thank you for this great plugin... When I click play on Arabic file names, nothing happens... Any idea?

**Comment by bizmarks** [comment]
Actually I figured out the solution to this problem. For anyone struggling with this, you may do the following: (keep in mind that MS Windows as far as my experience went, could not read the Arabic filenames, so I had to resort to CentOS Linux ; CentOS is free, open source and lightweight, so you can install it on a spare machine..).
Get Easytag from the file repository: #yum install -y easytag. If you get an error use #yum whatprovides */easytag to get the exact file repository name, then install using #yum install -y %repositoryName%
IMPORTANT: Make sure your server supports unicode encoding. Otherwise edit /etc/httpd/httpd.conf and uncomment the line that refers to utf8 encoding. OK, let's get our hands dirty!...

Once Easytag is installed, open it and batch edit the id3tags... MAKE SURE you go to the settings first and instruct the program NOT TO WRITE ID3V1 tags (as ID3v1 does not support unicode as far as I know) and write ID3V2 tags only. Once that setting is taken care of, all you have to do is batch edit TITLE TAGS on your folders, then rename files according to track number... To do that, take the following steps: 
*** Load folders
*** Highlight all files with SHIFT-Click or CTRL-A 
*** Right click on selected files, then point to scanner and FILL TAGS. On the tag box, enter %n. then click on the green button on the top bar. (This will tag the file with the actual filename that browsers could not render). CLOSE the fill tags dialogue box.
*** Next, with files still highlighted, click on the "#" button in front of Track (Look in the right side of the screen) . This will sequentially assign files track numbers.
**** With files still highlighted, right click again. point to scanner and select :"Rename Files and Directories"... In the edit field, enter %n. This will rename the files sequentially by track numbers... So files will not have unicode characters anymore but regular numbers like 01.mp3, 02.mp3 etc... However, the ID3 tag will be filled with the original filename which was the "unicode name". This unicode name will be rendered on the browser but when you click PLAY or DOWNLOAD, the browser will work on 01.mp3, 02.mp3 etc..... 
******** VERY IMPORTANT::::   CLICK ON FILE and SAVE FILES....
******MAKE sure you take these steps in the aforementioned order.

It would be a good idea to backup your files before manipulating them with easytag.

---- Repeat as needed on all folders... The beauty of easytag is that you can tell it to recurse through subfolders. So if you have one folder with 100 subfolders and 1000 tracks, simply load parent folder, select all and it will work its magic through your whole directory tree.

Disclaimer: This info is provided as is. This worked wonders for me and it should work for you as well. I am not responsible for any trouble that may arise from this. Use instructions as is. I think I listed all the steps but I may have overlooked one step or 2 (I doubt it but ....)... Use your intuition to figure out anything skipped and bring corrections for others to benefit from... I took time to write this because I struggled mightily with this. I went as far as editing Apache config files, .htaccess etc.. to no avail.

Good Luck!

**Comment by sverhagen** [comment]
Thanks for the thorough explanation. I did not validate any of it, but it may be useful for someone. I did link to it, though, from [this](https://www.totaalsoftware.com/products/mp3-browser/features) page.

**Comment by bizmarks** [comment]
You are very welcome. Thanks again for this great, great plugin!!
