### ISSUE TITLE
MP£ Browser on Apple/ipad

### ISSUE THREAD

**Issue by ramblerswebs** [sverhagen/mp3-browser#63]
I like this extension very much, but it does not seem to work on my Ipad.

Is this a bug or is this expected?

**Comment by bizmarks** [comment]
You have to fiddle with flash fallback/ html5 audio. In the advanced settings, you will have to add some code like 
<audio id="audioplayer" preload="metadata" type="audio/mp3" >
    
Your browser doesn't support the HTML audio tag.
</audio>

Just Google mp3browser flash fallback. I will share the steps with you tomorrow. Basically the iPad does not support flash, so you have to tell mp3browser to fallback to html5 audio on mobile devices if flash is not supported.

**Comment by bizmarks** [comment]
You have to fiddle with flash fallback/ html5 audio. In the advanced settings, you will have to add some code like 
audio id="audioplayer" preload="metadata" type="audio/mp3" 
    
Your browser doesn't support the HTML audio tag.
/audio
(Put brackets around audio opening and closing tags.)

Just Google mp3browser flash fallback. I will share the steps with you tomorrow. Basically the iPad does not support flash, so you have to tell mp3browser to fallback to html5 audio on mobile devices if flash is not supported.

**Comment by ramblerswebs** [comment]
thanks, I look forward to seeing the solution.
I wonder if the fix can be part of the extension?
Otherwise a very good player.

**Comment by ramblerswebs** [comment]
sorry to be a pain but it would be very good to hear what I need to do to get this working on Apple/ipads

**Comment by sverhagen** [comment]
Sorry for my slow response, but please see if [this](https://www.totaalsoftware.com/products/mp3-browser/documentation/145-alternative-player) works for you.

**Comment by ramblerswebs** [comment]
Hi
thanks for your help so far.
I have now had a look at this BUT am obviously missing something.
I believe I have added the js and css files to the page and changed the Advanced setting.
My test page is http://test.thepioneers.org.uk/articles/24-about-us/62-audio-archive-taster.html
The table of mp3 files displays ok with the player controls but after a second or two the player controls vanish.
I note that the source code is
<audio controls="">
<source type="audio/mpeg" src="//images/audio/audiotaster/Christmas Carol service of 1966.mp3"></source>
Your browser does not support the audio element.
</audio>
two things concern me the <audio controls=""> the ="" is not in the Advanced setting
and the scr= starts with //
my article has the statement {music}images/audio/audiotaster{/music} so not sure where the // comes from.
Are either of these stopping it working or is it something else?

I am not in to any of this so any help gratefully received

**Comment by sverhagen** [comment]
I noticed the `//images...` at the beginning of the `src` too. I used Firebug to fiddle with it, and it works when I change it to `src="http://test.thepioneers.org.uk/images/audio/..."`. Did  you try removing the `/` in "Player source code" (where it says `src="/%3"`)?

**Comment by ramblerswebs** [comment]
Hi,
I have a fiddle and changed the Advanced text to
<audio src="%3" type="audio/mp3" controls="controls">
</audio>

it seems to work fine, does it look ok to you?

Need to try it on an Apple yet - just tried on Ipad and while it does 
not display quite right (only the play button displayed) it does work

regards
Chris Vaughan
Derby & South Derbyshire Ramblers

support001@ramblers-webs.org.uk
Administrator Ramblers-webs.org.uk

**Comment by sverhagen** [comment]
If it works, that would trump looking it looking ok to me. My hypothesis is that I came up with the original `src="/%3"` on a system where Joomla wasn't mounted to the root of the context path. Good luck!
