### ISSUE TITLE
problem with php

### ISSUE THREAD

**Issue by frannyji** [sverhagen/mp3-browser#67]
Is the plugin going to be updated soon. My host at Siteground is not supporting php version pre 5.4. I had been testing this plugin and it was doing exactly what I wanted until a recent upgrade of php at host. Now I cannot save or use the plugin. The error message I get is:

_Deprecated: Non-static method FinderIndexer::index() should not be called statically, assuming $this from incompatible context in /home/.../public_html/plugins/finder/mp3smartsearch/mp3smartsearch.php on line 354

Fatal error: Cannot call abstract method FinderIndexer::index() in /home/.../public_html/plugins/finder/mp3smartsearch/mp3smartsearch.php on line 354_
I need to know if you can fix this. Thanks.
Blessings,
F

**Comment by Bear4** [comment]
I like very much this plugin. It's very useful. Thanks.
I want switch my site at PHP 7.0, so is there an chances to improve mp3-browser?
Many thanks in anticipation for an answer.

**Comment by davidascherG** [comment]
Does not work with Joomla 3.6.5 and PHP 7.1. No error message. Just blank screen.

Are you planning an update to deal with this??

**Comment by Jandaai** [comment]
Facing the same problem, does not work with PHP7. What to do???

**Comment by tdi2004** [comment]
The following worked for me:
I pulled mp3-browser/src/main/php/mp3browser/getid3/getid3/getid3.lib.php (42679 bytes) from github and replaced the old getid3.lib.php in /plugins/content/mp3browser/getid3/getid3 (44011 bytes). 
Then mp3browser worked for me under PHP 7.0 (and PHP 5.6, too)
AFAICS this lib has been the only change to make it running under PHP 7.0 - if not please comment and correct me.

**Comment by doctormix1978** [comment]
Thanks tdi2004. Your solution worked for me.

**Comment by davidascherG** [comment]
I'm no github expert and was unable to figure out how to 'pull' the
getid3.lib.php file from github. I finally found gitzip at
http://kinolien.github.io/gitzip/ and used that to download the entire
mp3-browser/src/main/php/mp3browser/getid3/getid3/directory and replaced
the file in getid2.lib.php file in
/plugins/content/mp3browser/getid3/getid3.... it looks like there is really
only a single line added to the new file.

**Comment by mschnye** [comment]
I just tried to run my site on php 7. Although I took the getid3.lib.php, it didn't work. On frontend I get following error 0 - "Class 'getid3_lib' not found".

Can anybody help me?

Keind regards,

Marco

**Comment by davidascherG** [comment]
are you sure you put the new library in the right place in the directory
tree??
 
 
 

  _____

**Comment by mschnye** [comment]
Hi, 

 

I Just find out, that I did a download instead of copy/paste. So there was a wrong content.

No, it works fine.

Thank you for fast responed.

 

 

 

Von: davidascherG [mailto:notifications@github.com] 
Gesendet: Mittwoch, 17. Mai 2017 21:34
An: sverhagen/mp3-browser <mp3-browser@noreply.github.com>
Cc: mschnye <marco.schnyder@2protect.ch>; Comment <comment@noreply.github.com>
Betreff: Re: [sverhagen/mp3-browser] problem with php (#67)

 

are you sure you put the new library in the right place in the directory
tree??




_____

**Comment by sverhagen** [comment]
Seems like people here describe a few different problems that mostly should have gotten fixed in cd08fe1 and e04335f. Solved in 0.4.0 ([released here](https://www.totaalsoftware.com/downloads/mp3-browser)). Feel free to get back to me if there are remaining issues.
