### ISSUE TITLE
no sound en no domain in download url

### ISSUE THREAD

**Issue by tuckson** [sverhagen/mp3-browser#68]
Hi Sander,

Installed mp3browser. Looks like exactly what I need, but can get it to work. I get a nice table on the page (though it takes some time to load).
However, The mp3's give no sound and the downloadlink is incorrect (it omits the servername)

Cheers

**Comment by tuckson** [comment]
hmmm.... downloadbutton goes ok if I omit a preceeding slash. So this goes wrong:
{music}/downloads/mp3{/music}
And this goes right: {music}downloads/mp3{/music}
Odd behavious ;-)

Am on work now. Will check  tonight if sounds works now as well.

**Comment by tuckson** [comment]
Sound works ok.
The only thing left is that it takes very long for the page to load. Are all mp3's preloaded or something like that?

**Comment by sverhagen** [comment]
I believe all the MP3s are inspected on the server's file system to extract the metadata. See [this description](https://www.totaalsoftware.com/products/mp3-browser/documentation/155-limitations).
