### ISSUE TITLE
MP3 Browser Fork not working in mobile

### ISSUE THREAD

**Issue by wilsonds75** [sverhagen/mp3-browser#70]
Hi,
MP3 Browser Fork not working in mobile
http://www.lloydtaccode.com/music-store/audio/101-album-moga-savlli-2015
Please suggest.

**Comment by SithlordIII** [comment]
http://thatband.co.uk

MP3 Browser Fork not working for mobile devices - got it working in desktop ok  ,   you can down load on mobile  but cant stream / play via google browser or standard android browser

**Comment by mhansk** [comment]
MP3 browser not working in 
PHP Version 5.6.31
Joomla! Version | Joomla! 3.7.5 Stable [ Amani ] 14-August-2017 12:09 GMT
http://tepoa.info/tecr-90-1fm-disk-jockeys/6-ken-johnson
Please ask if you need more info
thanks
Mara

**Comment by sverhagen** [comment]
There's no Flash on Android, so the default player doesn't work. Perhaps try an [alternative player](https://www.totaalsoftware.com/products/mp3-browser/documentation/145-alternative-player). It'd be great if some non-Flash player became the default, and I'd happily take a merge request for that.
