### ISSUE TITLE
Blank Screen when article with MP3 Fork is selected 

### ISSUE THREAD

**Issue by Scorptech** [sverhagen/mp3-browser#71]
Hi, 

I've attached the error code that comes up when I select the article with MP3 Fork in it. I just get a blank screen and nothing comes up? I'm using Joomla 3.7.2 with php 7. 

![mp3fork_error](https://cloud.githubusercontent.com/assets/28982200/26495774/c77fab84-421c-11e7-9bad-f64424477a6c.jpg)

This is a great plugin so I hope someone can find out what the problem is. 

Regards 

Alan

**Comment by sverhagen** [comment]
This got fixed in e04335f. Solved in 0.4.0 ([released here](https://www.totaalsoftware.com/downloads/mp3-browser)).
