### ISSUE TITLE
mp3 browser fork not working

### ISSUE THREAD

**Issue by bernardnijhof** [sverhagen/mp3-browser#73]
recently my joomla website updated on localhost with php 7.0. Unfortunately mp3 browser fork does not show any mp3 file.  It is said that there supposed to be a working upgrade 0.4.1. Where could I download this plugin?

**Comment by sverhagen** [comment]
Please try with 0.4.0 ([released here](https://www.totaalsoftware.com/downloads/mp3-browser)).
