### ISSUE TITLE
on Chrome the download column appears even if set to HIDE

### ISSUE THREAD

**Issue by aanconetani** [sverhagen/mp3-browser#74]
Hi I have a problem: I set the download column on hide.
On firefox the download column does not appear, if I open the same page on Chrome the download column appears
Can you help me? this is the link: http://www.lisciouno.com/index.php/dirette
Please look at the PODcast Direct form, here I have the problem!
Thank you

**Comment by aanconetani** [comment]
Please, can you help me?
Thank you

**Comment by sverhagen** [comment]
Sorry, I didn't see this until now. I'll have to look into better configuring GitHub notifications for myself. Are you still having this problem, I can't find this on your page anymore?
