### ISSUE TITLE
How can I delete or hide both columns "Download"

### ISSUE THREAD

**Issue by Radio7sk** [sverhagen/mp3-browser#75]
Hi, I want to ask you, how can I delete, or hide both columns of delete. I do not want to be able to download mp3 files. Or how can I changed different player? I am begginer in code. 

Thank you for your answer

**Comment by sverhagen** [comment]
Sorry, I didn't see this until now. I'll have to look into better configuring GitHub notifications for myself. Are you still having this problem? You should be able to remove the "Download" column using the configuration for the plugin.

![image](https://user-images.githubusercontent.com/2049860/42732142-38c212c4-87d0-11e8-83f8-c6e2f792b712.png)

(First option in the screenshot.)
