### ISSUE TITLE
Work on Smartphone

### ISSUE THREAD

**Issue by KnoSoft** [sverhagen/mp3-browser#76]
does the plugin work on the smartphone?

**Comment by KnoSoft** [comment]
Sorry, I pressed return too fast!
My name is Knobloch.
I think the plugin is great, but it does not seem to work on the smartphone.
Please answer

**Comment by samhnky** [comment]
I am able to use the plugin from my iPhone and Android phone... I wonder if you were using an older version of the plugin, or an older OS on your phone?

**Comment by sverhagen** [comment]
If you have updated an older version, the "Player source code" setting may still contain the old configuration. Should be:

    <audio controls preload="metadata" style="width: %1;"><source src="%3" type="audio/mpeg"><object width="%1" height="20" bgcolor="%2" data="%4" type="application/x-shockwave-flash"><param name="wmode" value="transparent" /><param name="movie" value="%4" /><param name="flashvars" value="mp3=%3" /></object></audio>
