### ISSUE TITLE
MP3-browser fork not working

### ISSUE THREAD

**Issue by SurfinTone** [sverhagen/mp3-browser#77]

**Comment by SurfinTone** [comment]
I want to use this mp3 player on my new website.
But the player does not show any files. What do I have to change?

Plugin is activated.
In my article I put the code: {music}nl/oefenfiles/207{/music}

There is a file in the directory.
You can check it: http://musicalvoices.nl/nl/oefenfiles/207/207.mp3

When I look on the page on my website I see the player with an message:
No parts to show (in Dutch "Geen onderdelen te tonen"

![image](https://user-images.githubusercontent.com/47530412/52736145-720e9100-2fc9-11e9-94aa-af43418ed2b2.png)

What do I wrong?

**Comment by sverhagen** [comment]
The value between the `{music}` tags needs to be the server path, relative to the root of the Joomla installation as well as the URL path, barring any rewrites. Sorry, I don't know why this wouldn't work for you. It's a while ago, sorry that I didn't see this earlier.
