### ISSUE TITLE
HTML5

### ISSUE THREAD

**Issue by mobielbas** [sverhagen/mp3-browser#79]
I see that mp3-browser now supports HTML5. But i don't see any changes. I still can't play mp3 on my mobile (android). Do i have to enable it?

**Comment by sverhagen** [comment]
If you have updated an older version, the "Player source code" setting may still contain the old configuration. Should be:

    <audio controls preload="metadata" style="width: %1;"><source src="%3" type="audio/mpeg"><object width="%1" height="20" bgcolor="%2" data="%4" type="application/x-shockwave-flash"><param name="wmode" value="transparent" /><param name="movie" value="%4" /><param name="flashvars" value="mp3=%3" /></object></audio>
