### ISSUE TITLE
version 0.4.1 still using Flash by default?

### ISSUE THREAD

**Issue by thepiston** [sverhagen/mp3-browser#81]
I'm using latest version which should have HTML5 support, but when it loads on my site, it loads as Flash and my browser does not allow it. Do I have to do anything to force HTML?

**Comment by thepiston** [comment]
actually, I see in the code that both HTML5 and flash tags are used. the source tag is not properly  coded though and I believe needs a tailing / at end (?)

**Comment by sverhagen** [comment]
[Mozilla suggests](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source) that `<source ...>` is valid (not `<source .../>` or `<source></source>`).

**Comment by thepiston** [comment]
got it, thanks
